env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
script:
- sudo apt-get install chromium-browser
- LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip && sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
- cd tests && ./testparallel.sh
- docker build -t docassemble .
before_deploy:
- eval $(aws ecr get-login --no-include-email --region us-west-2)
- docker tag docassemble:latest 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble:latest
deploy:
  provider: script
  script: docker push 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble:latest
  on:
    branch: master
