before_script:
- npx picaresque
jobs:
  include:
  - stage: terraform
    if: ( type = api ) AND ( branch = master )
    script:
    - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    - unzip terraform_0.11.11_linux_amd64.zip -d .
    - rm terraform_0.11.11_linux_amd64.zip
    - ./terraform init -backend-config="bucket=${TF_VAR_NAME}" -backend-config="key=main.tfstate"
    - ./terraform apply -auto-approve
