env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
addons:
  chrome: stable
before_script:
- eval $(aws ecr get-login --no-include-email --region us-east-1)
jobs:
  include:
  - stage: Build
    addons:
      chrome: stable
    if: type = push
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 1 101
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 101 201
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 201 301
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 301 401
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 401 501
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 501 601
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 601 701
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 701 801
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 801 901
  - stage: Test
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py 901 1001
