env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
addons:
  chrome: stable
before_script:
- eval $(aws ecr get-login --no-include-email --region us-east-1)
jobs:
  include:
  - stage: Build application
    if: type = push
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH 617580300246.dkr.ecr.us-east-1.amazonaws.com/docassemble:$TRAVIS_BRANCH
    - docker push 617580300246.dkr.ecr.us-east-1.amazonaws.com/docassemble:$TRAVIS_BRANCH
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 1 101
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 101 201
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 201 301
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 301 401
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 401 501
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 501 601
  - stage: Test application
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 1m
    - python tests/run.py 601 701
