language: python
before_script:
- export PATH=$PATH:$HOME/.local/bin
- pip install awscli chromedriver_installer lettuce lettuce_webdriver python-Levenshtein
- eval $(aws ecr get-login --no-include-email --region us-east-1)
jobs:
  include:
  - stage: Build
    services:
    - docker
    if: type = push
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
  - stage: Test
    addons:
      chrome: stable
    env:
    - START=1 END=101
    - START=101 END=201
    - START=201 END=301
    - START=301 END=401
    - START=401 END=501
    - START=501 END=601
    - START=601 END=701
    - START=701 END=801
    - START=801 END=901
    - START=901 END=1001
    if: type = push
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - sleep 5m
    - python tests/run.py $START $END
