env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
addons:
  chrome: stable
jobs:
  include:
  - stage: Build application
    script:
    - docker build -t docassemble-server .
    - docker tag docassemble-server:$TRAVIS_BRANCH 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - docker run -d -p 80:80 docassemble-server:$TRAVIS_BRANCH
    - lettuce tests/features/TestExamples.feature
    - eval $(aws ecr get-login --no-include-email --region us-west-2)
    - docker push 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
