language: python
services:
- docker
addons:
  chrome: stable
stages:
- name: build
  if: type = push
- name: test
  if: type = push
env:
- START=0 END=50
- START=50 END=100
- START=100 END=150
- START=150 END=200
- START=200 END=250
- START=250 END=300
- START=601 END=350
- START=701 END=400
- START=801 END=450
- START=901 END=500
- START=1 END=550
- START=101 END=600
- START=201 END=650
- START=301 END=700
- START=401 END=750
- START=501 END=800
- START=601 END=850
- START=701 END=900
- START=900 END=950
- START=950 END=1000
before_script:
- export PATH=$PATH:$HOME/.local/bin
- pip install awscli
- eval $(aws ecr get-login --no-include-email --region us-east-1)
script:
- docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
- pip install chromedriver_installer lettuce lettuce_webdriver python-Levenshtein
- python tests/run.py $START $END
jobs:
  include:
  - stage: build
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
