language: python

services:
- docker

script:
- docker build -t docassemble .

after_success:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag docassemble:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
  - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
