env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
addons:
  chrome: stable
before_script:
- eval $(aws ecr get-login --no-include-email --region us-west-2)
jobs:
  include:
  - stage: Build base
    if: type = api
    script:
    - cd base && docker build -t docassemble-base:latest .
    - docker tag docassemble-base:latest 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-base:latest
    - docker push 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-base:latest
  - stage: Build application
    if: type = push
    script:
    - docker build -t docassemble-server:$TRAVIS_BRANCH .
    - docker tag docassemble-server:$TRAVIS_BRANCH 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
    - docker run -d -p 80:80 docassemble-server:$TRAVIS_BRANCH
    - lettuce tests/features/TestExamples.feature
    - docker push 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-server:$TRAVIS_BRANCH
  - stage: Build application
    if: type = pull_request
    script: skip
