language: python
before_script:
- export PATH=$PATH:$HOME/.local/bin
- pip install awscli
- eval $(aws ecr get-login --no-include-email --region us-east-1)
stages:
- name: build
  if: type = push
- name: test
  if: type = push
jobs:
  include:
  - stage: build
    services: docker
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
  - stage: test
    addons:
      chrome: stable
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - pip install chromedriver_installer lettuce lettuce_webdriver python-Levenshtein
    - python tests/run.py $START $END
