language: python
services:
- docker
addons:
  chrome: stable
stages:
- name: build
  if: type = push
- name: test
  if: type = push
env:
- START=0 END=50
- START=50 END=100
- START=201 END=150
- START=301 END=200
- START=401 END=250
- START=501 END=300
- START=601 END=350
- START=701 END=400
- START=801 END=901
- START=901 END=1001
- START=1 END=101
- START=101 END=201
- START=201 END=301
- START=301 END=401
- START=401 END=501
- START=501 END=601
- START=601 END=701
- START=701 END=801
- START=801 END=901
- START=901 END=1001
before_script:
- export PATH=$PATH:$HOME/.local/bin
- pip install awscli
- eval $(aws ecr get-login --no-include-email --region us-east-1)
script:
- docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
- pip install chromedriver_installer lettuce lettuce_webdriver python-Levenshtein
- python tests/run.py $START $END
jobs:
  include:
  - stage: build
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
