language: python
services:
- docker
before_script:
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email)
jobs:
  include:
  - stage: build
    if: type = push
    script:
    - docker build -t ${TF_VAR_NAME}:$TRAVIS_BRANCH .
    - docker tag ${TF_VAR_NAME}:$TRAVIS_BRANCH $REPO_HOST/$TF_VAR_NAME:$TRAVIS_BRANCH
    - docker push $REPO_HOST/$TF_VAR_NAME:$TRAVIS_BRANCH
  - stage: terraform
    if: ( type = push ) AND ( branch = master )
    script:
    - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    - unzip terraform_0.11.7_linux_amd64.zip -d .
    - rm terraform_0.11.7_linux_amd64.zip
    - ./terraform init -backend-config="bucket=${TF_VAR_NAME}" -backend-config="key=main.tfstate"
    - ./terraform apply -auto-approve
