language: python
services:
- docker
addons:
  chrome: stable
env:
matrix:
  include:
  - env: START=1 END=101
  - env: START=101 END=201
  - env: START=201
    env: END=301
  - env: START=301
    env: END=401
  - env: START=401
    env: END=501
  - env: START=501
    env: END=601
  - env: START=601
    env: END=701
  - env: START=701
    env: END=801
  - env: START=801
    env: END=901
  - env: START=901
    env: END=1001
before_script:
- export PATH=$PATH:$HOME/.local/bin
- pip install awscli
- eval $(aws ecr get-login --no-include-email --region us-east-1)
stages:
- name: build
  if: type = push
- name: test
  if: type = push
jobs:
  include:
  - stage: build
    script:
    - docker build -t docassemble:$TRAVIS_BRANCH .
    - docker tag docassemble:$TRAVIS_BRANCH $REPO_URL:$TRAVIS_BRANCH
    - docker push $REPO_URL:$TRAVIS_BRANCH
  - stage: test
    script:
    - docker run -d -p 80:80 $REPO_URL:$TRAVIS_BRANCH
    - pip install chromedriver_installer lettuce lettuce_webdriver python-Levenshtein
    - python tests/run.py $START $END
