env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: python
services:
- docker
addons:
  chrome: stable
script:
- docker build -t docassemble .
- docker tag docassemble:latest 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble:latest
- docker run docassemble:latest /bin/bash -c "cd /tmp/docassemble/tests && PATH=$PATH:$HOME/.local/bin ./testparallel.sh"
before_deploy:
- eval $(aws ecr get-login --no-include-email --region us-west-2)
deploy:
  provider: script
  script: docker push 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble:latest
  on:
    branch: master
