FROM 617580300246.dkr.ecr.us-west-2.amazonaws.com/docassemble-base:latest
COPY . /tmp/docassemble/
RUN cp /tmp/docassemble/docassemble_webapp/docassemble.wsgi /usr/share/docassemble/webapp/ && cp /tmp/docassemble/Docker/*.sh /usr/share/docassemble/webapp/ && cp /tmp/docassemble/Docker/VERSION /usr/share/docassemble/webapp/ && cp /tmp/docassemble/Docker/pip.conf /usr/share/docassemble/local/ && cp /tmp/docassemble/Docker/config/* /usr/share/docassemble/config/ && cp /tmp/docassemble/Docker/cgi-bin/index.sh /usr/lib/cgi-bin/ && cp /tmp/docassemble/Docker/syslog-ng.conf /usr/share/docassemble/webapp/syslog-ng.conf && cp /tmp/docassemble/Docker/syslog-ng-docker.conf /usr/share/docassemble/webapp/syslog-ng-docker.conf && cp /tmp/docassemble/Docker/docassemble-syslog-ng.conf /usr/share/docassemble/webapp/docassemble-syslog-ng.conf && cp /tmp/docassemble/Docker/apache.logrotate /etc/logrotate.d/apache2 && cp /tmp/docassemble/Docker/docassemble.logrotate /etc/logrotate.d/docassemble && cp /tmp/docassemble/Docker/cron/docassemble-cron-monthly.sh /etc/cron.monthly/docassemble && cp /tmp/docassemble/Docker/cron/docassemble-cron-weekly.sh /etc/cron.weekly/docassemble && cp /tmp/docassemble/Docker/cron/docassemble-cron-daily.sh /etc/cron.daily/docassemble && cp /tmp/docassemble/Docker/cron/docassemble-cron-hourly.sh /etc/cron.hourly/docassemble && cp /tmp/docassemble/Docker/docassemble.conf /etc/apache2/conf-available/ && cp /tmp/docassemble/Docker/docassemble-behindlb.conf /etc/apache2/conf-available/ && cp /tmp/docassemble/Docker/docassemble-supervisor.conf /etc/supervisor/conf.d/docassemble.conf && cp /tmp/docassemble/Docker/ssl/* /usr/share/docassemble/certs/ && cp /tmp/docassemble/Docker/rabbitmq.config /etc/rabbitmq/ && cp /tmp/docassemble/Docker/config/exim4-router /etc/exim4/conf.d/router/101_docassemble && cp /tmp/docassemble/Docker/config/exim4-filter /etc/exim4/docassemble-filter && cp /tmp/docassemble/Docker/config/exim4-main /etc/exim4/conf.d/main/01_docassemble && cp /tmp/docassemble/Docker/config/exim4-acl /etc/exim4/conf.d/acl/29_docassemble && cp /tmp/docassemble/Docker/config/exim4-update /etc/exim4/update-exim4.conf.conf && update-exim4.conf
RUN chown www-data.www-data /usr/share/docassemble/config && chown www-data.www-data /usr/share/docassemble/config/config.yml.dist /usr/share/docassemble/webapp/docassemble.wsgi && chown -R www-data.www-data /tmp/docassemble /usr/share/docassemble/local /usr/share/docassemble/log /usr/share/docassemble/files && chmod ogu+r /usr/share/docassemble/config/config.yml.dist && chmod 755 /etc/ssl/docassemble
USER www-data
RUN pip install /tmp/docassemble/docassemble /tmp/docassemble/docassemble_base /tmp/docassemble/docassemble_demo /tmp/docassemble/docassemble_webapp
USER root
RUN rm -rf /tmp/docassemble
EXPOSE 80 443 9001 514 25 465 8080 8081 5432 6379 4369 5671 5672 25672
ENV CONTAINERROLE="all" LOCALE="en_US.UTF-8 UTF-8" TIMEZONE="America/New_York" EC2="" S3ENABLE="" S3BUCKET="" S3ACCESSKEY="" S3SECRETACCESSKEY="" DAHOSTNAME="" USEHTTPS="" USELETSENCRYPT="" LETSENCRYPTEMAIL="" DBHOST="" LOGSERVER="" REDIS="" RABBITMQ=""
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
